version = "2.5.3"

local supported_languages = {
    en = true,
    zh = true,
    de = true,
    es = true,
    fr = true,
    ru = true,
    ko = true,
}

local language = (locale == "zh" or locale == "zhr") and "zh" or (locale and supported_languages[locale] and locale) or "en"

local config_strings = {
    strings = {
        name = {
            en = "Wormholes/Sinkholes Icons For Server",
            zh = "Wormholes/Sinkholes Icons For Server 虫洞/天坑的服务器图标",
            de = "Wurmlöcher/Sinklöcher Icons für Server",
            es = "Iconos de agujeros de gusano y sumideros para el servidor",
            fr = "Icônes Wormholes/Sinkholes pour le serveur",
            ru = "Иконки червоточин/провалов для сервера",
            ko = "서버용 웜홀/싱크홀 아이콘",
        },
        description = {
            en = "This mod gives Wormhole and Sinkholes Icons to every person on the server, but everyone has the same numbers!\nThis makes it easier to communicate with each other!\n You can also rename the wormholes and sinkholes so that you also know to where they lead!\nSinkholes also automatically have the same color on the surface and in the caves!",
            zh = "这个mod给服务器上的每个人都提供了虫洞和天坑的图标，但每个人都有相同的数字！这使得彼此之间的沟通更加容易。\n这使得彼此之间的沟通更加容易!\n你也可以给虫洞和天坑重命名，这样你也可以知道它们通向哪里!\n天坑在表面和洞穴中也自动具有相同的颜色!",
            de = "Dieser Mod gibt jeder Person auf dem Server Wurmloch- und Sinkholes-Icons, aber alle haben die gleichen Nummern!\nDas macht es einfacher, miteinander zu kommunizieren!\nDu kannst die Wurmlöcher und Sinkholes auch umbenennen, damit du auch weißt, wohin sie führen!\nSinkholes haben auch automatisch die gleiche Farbe an der Oberfläche und in den Höhlen!",
            es = "Este mod da iconos de agujeros de gusano y sumideros a cada persona en el servidor, pero todo el mundo tiene los mismos números! Esto hace que sea más fácil comunicarse entre sí! También puede cambiar el nombre de los agujeros de gusano y sumideros para que también sepa a dónde conducen!",
            fr = "Ce mod donne des icônes de vortex et de dolines à chaque personne sur le serveur, mais tout le monde a les mêmes numéros !\nCe qui rend plus facile la communication avec les autres !\nVous pouvez également renommer les vortex et les dolines afin que vous sachiez où ils mènent !\nLes dolines ont aussi automatiquement la même couleur à la surface et dans les cavernes !",
            ru = "Этот мод дает значки червоточин и воронок каждому человеку на сервере, но у всех одинаковые номера!\nЭто облегчает общение друг с другом!\nВы также можете переименовать червоточины и воронки, чтобы знать, куда они ведут!\nВоронки также автоматически имеют один и тот же цвет на поверхности и в пещерах!",
            ko = "이 모드는 서버의 모든 사람에게 웜홀과 싱크홀 아이콘을 제공하지만 모든 사람이 동일한 번호를 갖습니다!\n이것은 서로 의사 소통을 더 쉽게 만듭니다!\n웜홀과 싱크홀의 이름을 변경하여 어디로 이어지는지 알 수 있습니다!\n싱크홀은 또한 표면과 동굴에서 자동으로 동일한 색상을 갖습니다!",
        },
    },
    bool = {
        ["true"] = {
            en = "Yes",
            zh = "是的",
            de = "Ja",
            es = "Sí",
            fr = "Oui",
            ru = "Да",
            ko = "예",
        },
        ["false"] = {
            en = "No",
            zh = "没有",
            de = "Nein",
            es = "No",
            fr = "Non",
            ru = "Нет",
            ko = "아니요",
        },
    },
    color_names = {
        {
            en = "Red",
            zh = "红色",
            de = "Rot",
            es = "Rojo",
            fr = "Rouge",
            ru = "Красный",
            ko = "빨간색",
        },
        {
            en = "Green",
            zh = "绿色",
            de = "Grün",
            es = "Verde",
            fr = "Vert",
            ru = "Зеленый",
            ko = "녹색",
        },
        {
            en = "Yellow",
            zh = "黄",
            de = "Gelb",
            es = "Amarillo",
            fr = "Jaune",
            ru = "Желтый",
            ko = "노란색",
        },
        {
            en = "Blue",
            zh = "蓝",
            de = "Blau",
            es = "Azul",
            fr = "Bleu",
            ru = "Голубой",
            ko = "파란색",
        },
        {
            en = "Orange",
            zh = "橙色",
            de = "Orange",
            es = "Naranja",
            fr = "Orange",
            ru = "Оранжевый",
            ko = "오렌지",
        },
        {
            en = "Purple",
            zh = "紫色",
            de = "Lila",
            es = "Morado",
            fr = "Pourpre",
            ru = "Фиолетовый",
            ko = "보라색",
        },
        {
            en = "Cyan",
            zh = "青色",
            de = "Cyan",
            es = "Cian",
            fr = "Cyan",
            ru = "Cyan",
            ko = "Cyan",
        },
        {
            en = "Magenta",
            zh = "品红",
            de = "Magenta",
            es = "Magenta",
            fr = "Magenta",
            ru = "Magenta",
            ko = "마젠타",
        },
        {
            en = "Lime",
            zh = "青色",
            de = "Limette",
            es = "Cal",
            fr = "Chaux",
            ru = "Лайм",
            ko = "라임",
        },
        {
            en = "Pink",
            zh = "粉红色",
            de = "Rosa",
            es = "Rosa",
            fr = "Rose",
            ru = "Розовый",
            ko = "핑크",
        },
        {
            en = "Teal",
            zh = "青色",
            de = "Türkisblau",
            es = "Teal",
            fr = "Sarcelle",
            ru = "Тиль",
            ko = "청록색",
        },
        {
            en = "Lavender",
            zh = "薰衣草色",
            de = "Lavendel",
            es = "Lavanda",
            fr = "Lavande",
            ru = "Лаванда",
            ko = "라벤더",
        },
        {
            en = "Brown",
            zh = "棕色",
            de = "Braun",
            es = "Marrón",
            fr = "Marron",
            ru = "Коричневый",
            ko = "브라운",
        },
        {
            en = "Beige",
            zh = "米色",
            de = "Beige",
            es = "Beige",
            fr = "Beige",
            ru = "Бежевый",
            ko = "베이지",
        },
        {
            en = "Maroon",
            zh = "栗色",
            de = "Kastanienbraun",
            es = "Granate",
            fr = "Marron",
            ru = "Maroon",
            ko = "Maroon",
        },
        {
            en = "Mint",
            zh = "薄荷色",
            de = "Minze",
            es = "Menta",
            fr = "Menthe",
            ru = "Мята",
            ko = "민트",
        },
        {
            en = "Olive",
            zh = "橄榄色",
            de = "Olive",
            es = "Oliva",
            fr = "Olive",
            ru = "Олива",
            ko = "올리브",
        },
        {
            en = "Apricot",
            zh = "杏色",
            de = "Aprikose",
            es = "Albaricoque",
            fr = "Abricot",
            ru = "Абрикос",
            ko = "살구",
        },
        {
            en = "Navy",
            zh = "海军",
            de = "Marine",
            es = "Marina",
            fr = "Marine",
            ru = "ВМФ",
            ko = "해군",
        },
        {
            en = "Grey",
            zh = "灰色",
            de = "Grau",
            es = "Gris",
            fr = "Gris",
            ru = "Серый",
            ko = "회색",
        },
    },
    ["Utility Options"] = {
        en = "Utility Options",
        zh = "公用事业选项",
        de = "Utility-Optionen",
        es = "Opciones de utilidad",
        fr = "Options d'utilité",
        ru = "Варианты использования",
        ko = "유틸리티 옵션",
    },
    getWormholeColorOptions = {
        label = {
            en = "Wormhole Color ",
            zh = "虫洞的颜色 ",
            de = "Wurmloch Farbe",
            es = "Color del agujero de gusano",
            fr = "Couleur du trou de ver",
            ru = "Цвет червонца",
            ko = "웜홀 색상",
        },
        hover1 = {
            en = "Choose the color of the ",
            zh = "选择第",
            de = "Wählen Sie die Farbe des",
            es = "Elija el color del",
            fr = "Choisissez la couleur de la",
            ru = "Выберите цвет",
            ko = "색상을 선택합니다.",
        },
        hover2 = {
            en = "-th wormhole pair.",
            zh = "个天坑对的颜色。",
            de = "-ten Wurmloch-Paar.",
            es = "-Enésimo par de agujeros de gusano.",
            fr = "-ième paire de vortex.",
            ru = "-я пара червоточин.",
            ko = "-번째 웜홀 쌍입니다.",
        },
    },
    getSinkholeColorOptions = {
        label = {
            en = "Sinkhole Color ",
            zh = "天坑颜色 ",
            de = "Farbe des Sinklochs",
            es = "Color del sumidero",
            fr = "Couleur de l'aven",
            ru = "Цвет воронки",
            ko = "싱크홀 색상",
        },
        hover1 = {
            en = "Choose the color of the ",
            zh = "选择第",
            de = "Wählen Sie die Farbe des",
            es = "Elija el color del",
            fr = "Choisissez la couleur de la",
            ru = "Выберите цвет",
            ko = "색상을 선택합니다.",
        },
        hover2 = {
            en = "-th sinkhole pair.",
            zh = "个天坑对的颜色。",
            de = "-Lochpaar.",
            es = "-par de sumideros.",
            fr = "-ème paire de gouffres.",
            ru = "-я пара воронок.",
            ko = "-번째 싱크홀 쌍입니다.",
        },
    },
    LANGUAGE = {
        label = {
            en = "Language",
            zh = "语言",
            de = "Sprache",
            es = "Idioma",
            fr = "Langue",
            ru = "Язык",
            ko = "언어",
        },
        hover = {
            en = "Choose the language of this mod.",
            zh = "选择本模式的语言。",
            de = "Wählen Sie die Sprache dieses Mods.",
            es = "Elige el idioma de este mod.",
            fr = "Choisissez la langue de ce module.",
            ru = "Выберите язык этого мода.",
            ko = "이 모드의 언어를 선택하세요.",
        },
    },
    SANITY = {
        label = {
            en = "Sanity Penalty",
            zh = "理智的刑罚",
            de = "Sanitätsstrafe",
            es = "Sanción de cordura",
            fr = "Sanity Penalty",
            ru = "Штраф за вредность",
            ko = "정신력 페널티",
        },
        hover = {
            en = "Define if and how much sanity should be substracted when going through a wormhole.",
            zh = "界定在穿越虫洞时是否应该减去多少理智，以及减去多少理智。",
            de = "Legen Sie fest, ob und wie viel Vernunft beim Durchqueren eines Wurmlochs abgezogen werden soll.",
            es = "Definir si se debe restar cordura al atravesar un agujero de gusano y cuánto.",
            fr = "Définir si et dans quelle mesure la santé mentale doit être réduite lors de la traversée d'un trou de ver.",
            ru = "Определите, нужно ли вычитать здравый смысл при прохождении через червоточину и если да, то сколько.",
            ko = "웜홀을 통과할 때 정신 상태를 추상화할지 여부와 그 정도를 정의합니다.",
        },
    },
    ICON_PLACEMENT = {
        label = {
            en = "Name/Number Placement",
            zh = "名称/编号的放置",
            de = "Name/Nummer Platzierung",
            es = "Nombre/Número Colocación",
            fr = "Nom/Numéro Placement",
            ru = "Размещение имени/номера",
            ko = "이름/번호 배치",
        },
        hover = {
            en = "Decide where the number/name of the wormhole/sinkhole should be placed on the map and/or minimap.",
            zh = "决定虫洞/水坑的编号/名称应该放在地图和/或最小地图上的什么位置。",
            de = "Entscheiden Sie, wo die Nummer/der Name des Wurmlochs/Sinklochs auf der Karte und/oder Minimap platziert werden soll.",
            es = "Decide dónde debe colocarse el número/nombre del agujero de gusano/sumidero en el mapa y/o minimapa.",
            fr = "Décider de l'emplacement du numéro/nom du vortex/trou d'eau sur la carte et/ou la minimap.",
            ru = "Решите, где на карте и/или миникарте должен быть размещен номер/название червоточины/затонувшего объекта.",
            ko = "지도 및/또는 미니맵에서 웜홀/싱크홀의 번호/이름을 어디에 배치할지 결정합니다.",
        },
        options = {
            {
                description = {
                    en = "Hover",
                    zh = "徘徊",
                    de = "Schweben",
                    es = "Hover",
                    fr = "Survolez",
                    ru = "Hover",
                    ko = "호버",
                },
                hover = {
                    en = "Only appears when hovering over the wormhole/sinkhole",
                    zh = "只在悬停在虫洞/天坑上时出现",
                    de = "Erscheint nur, wenn man über dem Wurmloch/Sinkloch schwebt",
                    es = "Sólo aparece cuando se cierne sobre el agujero de gusano/hundidero.",
                    fr = "N'apparaît que lorsque l'on survole le vortex ou le trou noir.",
                    ru = "Появляется только при наведении на червоточину/воронку",
                    ko = "웜홀/싱크홀 위에 마우스를 올려놓을 때만 나타납니다.",
                },
            },
            {
                description = {
                    en = "Above",
                    zh = "以上",
                    de = "Über",
                    es = "Por encima de",
                    fr = "Au-dessus",
                    ru = "Выше",
                    ko = "위",
                },
                hover = {
                    en = "Placed above the image of the wormhole/sinkhole",
                    zh = "放在虫洞/沉降孔的图像上方",
                    de = "Platziert über dem Bild des Wurmlochs/Sinklochs",
                    es = "Situado encima de la imagen del agujero de gusano/hundidero",
                    fr = "Placé au-dessus de l'image du trou de ver/sinkhole",
                    ru = "Размещается над изображением червоточины/раковины",
                    ko = "웜홀/싱크홀 이미지 위에 배치됩니다.",
                },
            },
            {
                description = {
                    en = "On top",
                    zh = "在上面",
                    de = "Oben",
                    es = "Arriba",
                    fr = "En haut",
                    ru = "На вершине",
                    ko = "상단",
                },
                hover = {
                    en = "Placed on top of the image of the wormhole/sinkhole",
                    zh = "放在虫洞/沉降孔的图像之上",
                    de = "Wird über das Bild des Wurmlochs/Sinklochs gelegt",
                    es = "Colocado encima de la imagen del agujero de gusano/hundidero",
                    fr = "Placé au-dessus de l'image du trou de ver/sinkhole",
                    ru = "Размещается поверх изображения червоточины/раковины",
                    ko = "웜홀/싱크홀 이미지 위에 배치됩니다.",
                },
            },
            {
                description = {
                    en = "Below",
                    zh = "下图",
                    de = "Unter",
                    es = "Abajo",
                    fr = "En dessous",
                    ru = "Ниже",
                    ko = "아래",
                },
                hover = {
                    en = "Placed below the image of the wormhole/sinkhole",
                    zh = "放在虫洞/天坑的图像下面",
                    de = "Platziert unter dem Bild des Wurmlochs/Sinklochs",
                    es = "Colocado debajo de la imagen del agujero de gusano/hundidero",
                    fr = "Placé sous l'image du trou de ver/sinkhole",
                    ru = "Размещается под изображением червоточины/раковины",
                    ko = "웜홀/싱크홀 이미지 아래에 배치됩니다.",
                },
            },
            {
                description = {
                    en = "Left",
                    zh = "左边",
                    de = "Links",
                    es = "Izquierda",
                    fr = "Gauche",
                    ru = "Левый",
                    ko = "왼쪽",
                },
                hover = {
                    en = "Placed left of the image of the wormhole/sinkhole",
                    zh = "放在虫洞/天坑图像的左边",
                    de = "Links neben dem Bild des Wurmlochs/Sinklochs platziert",
                    es = "Situado a la izquierda de la imagen del agujero de gusano/hundidero",
                    fr = "Placé à gauche de l'image du trou de ver/sinkhole",
                    ru = "Размещается слева от изображения червоточины/раковины",
                    ko = "웜홀/싱크홀 이미지 왼쪽 배치",
                },
            },
            {
                description = {
                    en = "Right",
                    zh = "对",
                    de = "Rechts",
                    es = "Derecha",
                    fr = "Droit",
                    ru = "Справа",
                    ko = "오른쪽",
                },
                hover = {
                    en = "Placed right of image of the wormhole/sinkhole",
                    zh = "放在虫洞/天坑图像的右边",
                    de = "Rechts vom Bild des Wurmlochs/Sinklochs platziert",
                    es = "Situado a la derecha de la imagen del agujero de gusano/hundidero",
                    fr = "Placé à droite de l'image du trou de ver/sinkhole",
                    ru = "Размещается справа от изображения червоточины/раковины",
                    ko = "웜홀/싱크홀 이미지 오른쪽 배치",
                },
            },
        },
    },
    RENAME_FROM_MAP = {
        label = {
            en = "Rename from map",
            zh = "从地图上重命名",
            de = "Von Karte umbenennen",
            es = "Renombrar desde mapa",
            fr = "Renommer à partir de la carte",
            ru = "Переименование из карты",
            ko = "지도에서 이름 바꾸기",
        },
        hover = {
            en = "Decide whether you want to be able to rename wormholes/sinkholes from the map",
            zh = "决定你是否希望能够从地图上重新命名虫洞/天坑",
            de = "Entscheiden Sie, ob Sie Wurmlöcher/Sinklöcher auf der Karte umbenennen können möchten",
            es = "Decide si quieres poder renombrar los agujeros de gusano o sumideros desde el mapa.",
            fr = "Décidez si vous voulez pouvoir renommer les trous de ver/trous d'épingle à partir de la carte.",
            ru = "Решите, хотите ли вы иметь возможность переименовывать червоточины/раковины с карты",
            ko = "맵에서 웜홀/싱크홀의 이름을 변경할 수 있는지 여부를 결정합니다.",
        },
    },
    ["Wormhole Icon Options"] = {
        en = "Wormhole Icon Options",
        zh = "虫洞图标选项",
        de = "Wurmloch-Symbol Optionen",
        es = "Opciones de iconos de agujeros de gusano",
        fr = "Options de l'icône du vortex",
        ru = "Варианты значков червоточин",
        ko = "웜홀 아이콘 옵션",
    },
    FOR_ALL = {
        label = {
            en = "Icons For All",
            zh = "所有人的图标",
            de = "Icons für alle",
            es = "Iconos para todos",
            fr = "Icônes pour tous",
            ru = "Значки для всех",
            ko = "모두를 위한 아이콘",
        },
        hover = {
            en = "Choose if icons should be displayed for everyone even if they didn't go through the wormhole or just for those that went through them.",
            zh = "选择是否应该为每个人显示图标， 即使他们没有穿过虫洞，还是只为那些穿过虫洞的人显示。",
            de = "Legen Sie fest, ob die Symbole für alle angezeigt werden sollen, auch wenn sie nicht durch das Wurmloch gegangen sind, oder nur für diejenigen, die durch das Wurmloch gegangen sind.",
            es = "Elige si los iconos deben mostrarse para todos aunque no hayan atravesado el agujero de gusano o sólo para los que lo hayan atravesado.",
            fr = "Choisissez si les icônes doivent être affichées pour tout le monde, même s'ils n'ont pas traversé le vortex, ou seulement pour ceux qui l'ont traversé.",
            ru = "Выберите, должны ли значки отображаться для всех, даже если они не прошли через червоточину, или только для тех, кто прошел через нее.",
            ko = "웜홀을 통과하지 않은 모든 사람에게 아이콘을 표시할지, 아니면 통과한 사람에게만 아이콘을 표시할지 선택합니다.",
        },
        options = {
            {
                description = {
                    en = "For Everyone",
                    zh = "为每个人服务",
                    de = "Für alle",
                    es = "Para todos",
                    fr = "Pour tous",
                    ru = "Для всех",
                    ko = "모두를 위한",
                },
                hover = {
                    en = "Everyone will see all discovered wormholes on the map",
                    zh = "每个人都会在地图上看到所有发现的虫洞",
                    de = "Jeder wird alle entdeckten Wurmlöcher auf der Karte sehen",
                    es = "Todo el mundo verá todos los agujeros de gusano descubiertos en el mapa",
                    fr = "Tout le monde verra tous les vortex découverts sur la carte.",
                    ru = "Все увидят на карте все обнаруженные червоточины",
                    ko = "발견된 모든 웜홀을 지도에서 볼 수 있습니다.",
                },
            },
            {
                description = {
                    en = "For One",
                    zh = "为一",
                    de = "Für einen",
                    es = "Para uno",
                    fr = "Pour une personne",
                    ru = "Для одного",
                    ko = "하나",
                },
                hover = {
                    en = "Only those that went through the wormhole will see them on the map",
                    zh = "只有那些穿过虫洞的人才能在地图上看到他们。",
                    de = "Nur diejenigen, die durch das Wurmloch gegangen sind, sehen sie auf der Karte",
                    es = "Sólo los que pasaron por el agujero de gusano los verán en el mapa",
                    fr = "Seuls ceux qui ont traversé le trou de ver les verront sur la carte.",
                    ru = "Только те, кто прошел через червоточину, увидят их на карте",
                    ko = "웜홀을 통과한 사람만 지도에서 볼 수 있습니다.",
                },
            },
        },
    },
    RENAMING = {
        label = {
            en = "Renamable Wormholes",
            zh = "可重命名的虫洞",
            de = "Umbenennbare Wurmlöcher",
            es = "Agujeros de gusano renombrables",
            fr = "Trous de ver renommables",
            ru = "Переименовываемые червоточины",
            ko = "이름 변경 가능한 웜홀",
        },
        hover = {
            en = "Choose if wormholes can be renamed and by whom.",
            zh = "选择虫洞是否可以被重新命名，以及由谁来命名。",
            de = "Wählen Sie, ob und von wem Wurmlöcher umbenannt werden können.",
            es = "Elige si los agujeros de gusano pueden ser renombrados y por quién.",
            fr = "Choisissez si les vortex peuvent être renommés et par qui.",
            ru = "Выберите, могут ли червоточины быть переименованы и кем.",
            ko = "웜홀의 이름을 변경할 수 있는지, 누가 변경할 수 있는지 선택하세요.",
        },
        options = {
            {
                description = {
                    en = "Not renameable",
                    zh = "不可重命名",
                    de = "Nicht umbenennbar",
                    es = "No renombrable",
                    fr = "Non renommable",
                    ru = "Не переименовывается",
                    ko = "이름 변경 불가",
                },
            },
            {
                description = {
                    en = "For Everyone",
                    zh = "为每个人服务",
                    de = "Für alle",
                    es = "Para todos",
                    fr = "Pour tous",
                    ru = "Для всех",
                    ko = "모두를 위한",
                },
            },
            {
                description = {
                    en = "By Admins",
                    zh = "由管理员提供",
                    de = "Von Admins",
                    es = "Por Admins",
                    fr = "Par les administrateurs",
                    ru = "Администраторами",
                    ko = "관리자",
                },
            },
        },
    },
    SHOW_NUMBERS = {
        label = {
            en = "Display Numbers/Name",
            zh = "显示号码/名称",
            de = "Nummern/Namen anzeigen",
            es = "Mostrar números/nombre",
            fr = "Affichage des numéros/noms",
            ru = "Отображение номеров/имен",
            ko = "번호/이름 표시",
        },
        hover = {
            en = "Display numbers or names on wormhole map icons.",
            zh = "在虫洞地图图标上显示数字或名称。",
            de = "Anzeige von Zahlen oder Namen auf Wurmlochkartensymbolen.",
            es = "Mostrar números o nombres en los iconos del mapa de agujeros de gusano.",
            fr = "Afficher des nombres ou des noms sur les icônes de la carte des vortex.",
            ru = "Отображение чисел или имен на значках карт червоточин.",
            ko = "웜홀 지도 아이콘에 숫자나 이름을 표시합니다.",
        },
        options = {
            {
                description = {
                    en = "Nothing",
                    zh = "没有什么",
                    de = "Nichts",
                    es = "Nada",
                    fr = "Rien",
                    ru = "Ничего",
                    ko = "아무것도",
                },
            },
            {
                description = {
                    en = "Only Numbers",
                    zh = "只有数字",
                    de = "Nur Zahlen",
                    es = "Sólo números",
                    fr = "Uniquement des chiffres",
                    ru = "Только цифры",
                    ko = "숫자만",
                },
            },
            {
                description = {
                    en = "Only Names",
                    zh = "只有名字",
                    de = "Nur Namen",
                    es = "Sólo nombres",
                    fr = "Seuls les noms",
                    ru = "Только имена",
                    ko = "이름만",
                },
            },
            {
                description = {
                    en = "Numbers/Name",
                    zh = "编号/名称",
                    de = "Nummern/Namen",
                    es = "Números/Nombre",
                    fr = "Numéros/Noms",
                    ru = "Номера/название",
                    ko = "번호/이름",
                },
            },
        },
    },
    WORLD_COLORS = {
        label = {
            en = "World Colors",
            zh = "世界的颜色",
            de = "Farben der Welt",
            es = "Colores del mundo",
            fr = "Couleurs du monde",
            ru = "Краски мира",
            ko = "월드 컬러",
        },
        hover = {
            en = "Add coloring to wormholes in world",
            zh = "为世界上的虫洞添加颜色",
            de = "Wurmlöcher in der Welt einfärben",
            es = "Añadir color a los agujeros de gusano en el mundo",
            fr = "Ajouter des couleurs aux trous de ver dans le monde",
            ru = "Добавить окраску червоточинам в мире",
            ko = "월드의 웜홀에 컬러링 추가하기",
        },
    },
    WORLD_NUMBERS = {
        label = {
            en = "World Numbers/Name",
            zh = "世界号码/名称",
            de = "Welt-Nummern/Name",
            es = "Números mundiales/Nombre",
            fr = "Numéros/nom du monde",
            ru = "Мировые номера/названия",
            ko = "세계 번호/이름",
        },
        hover = {
            en = "Add a number or the given name above wormholes in the world",
            zh = "在世界的虫洞上方添加一个数字或给定的名称",
            de = "Hinzufügen einer Nummer oder eines Namens über Wurmlöcher in der Welt",
            es = "Añadir un número o el nombre dado por encima de los agujeros de gusano en el mundo",
            fr = "Ajouter un numéro ou un prénom au-dessus des trous de ver dans le monde",
            ru = "Добавить номер или имя над червоточинами в мире",
            ko = "월드의 웜홀 위에 숫자 또는 지정된 이름을 추가합니다.",
        },
        options = {
            {
                description = {
                    en = "Nothing",
                    zh = "没有什么",
                    de = "Nichts",
                    es = "Nada",
                    fr = "Rien",
                    ru = "Ничего",
                    ko = "아무것도",
                },
            },
            {
                description = {
                    en = "Only Numbers",
                    zh = "只有数字",
                    de = "Nur Zahlen",
                    es = "Sólo números",
                    fr = "Uniquement des chiffres",
                    ru = "Только цифры",
                    ko = "숫자만",
                },
            },
            {
                description = {
                    en = "Only Names",
                    zh = "只有名字",
                    de = "Nur Namen",
                    es = "Sólo nombres",
                    fr = "Seuls les noms",
                    ru = "Только имена",
                    ko = "이름만",
                },
            },
            {
                description = {
                    en = "Numbers/Name",
                    zh = "编号/名称",
                    de = "Nummern/Namen",
                    es = "Números/Nombre",
                    fr = "Numéros/Noms",
                    ru = "Номера/название",
                    ko = "번호/이름",
                },
            },
        },
    },
    WORMHOLE_BORDER = {
        label = {
            en = "Wormhole Border",
            zh = "虫洞边界",
            de = "Wurmloch-Grenze",
            es = "Frontera de agujeros de gusano",
            fr = "Bordure de trou de ver",
            ru = "Граница червоточины",
            ko = "웜홀 테두리",
        },
        hover = {
            en = "Add a colored border to wormholes in world",
            zh = "为世界上的虫洞添加彩色边框",
            de = "Wurmlöcher in der Welt mit einem farbigen Rand versehen",
            es = "Añadir un borde de color a los agujeros de gusano en el mundo",
            fr = "Ajouter une bordure colorée aux trous de ver dans le monde",
            ru = "Добавить цветную рамку к червоточинам в мире",
            ko = "월드의 웜홀에 컬러 테두리 추가하기",
        },
    },
    MINIMAP_ICONS = {
        label = {
            en = "Minimap Icons",
            zh = "迷你地图图标",
            de = "Minimap-Symbole",
            es = "Iconos del minimapa",
            fr = "Icônes de mini-carte",
            ru = "Значки минимальной карты",
            ko = "미니맵 아이콘",
        },
        hover = {
            en = "Display wormhole icons on the minimap",
            zh = "在最小地图上显示虫洞图标",
            de = "Anzeige von Wurmlochsymbolen auf der Minimap",
            es = "Mostrar iconos de agujeros de gusano en el minimapa",
            fr = "Afficher les icônes des vortex sur la minimap",
            ru = "Отображение значков червоточин на миникарте",
            ko = "미니맵에 웜홀 아이콘 표시하기",
        },
    },
    ["Sinkhole Icon Options"] = {
        en = "Sinkhole Icon Options",
        zh = "天坑图标选项",
        de = "Optionen für das Sinkloch-Symbol",
        es = "Opciones de iconos de sumideros",
        fr = "Options d'icônes de dolines",
        ru = "Варианты значков карстовых воронок",
        ko = "싱크홀 아이콘 옵션",
    },
    SINKHOLES = {
        label = {
            en = "Sinkhole Icons",
            zh = "天坑图标",
            de = "Sinkloch-Symbole",
            es = "Iconos de sumideros",
            fr = "Icônes de dolines",
            ru = "Значки карстовых воронок",
            ko = "싱크홀 아이콘",
        },
        hover = {
            en = "Choose if you want to enable sinkhole icons",
            zh = "选择是否要启用天坑图标",
            de = "Wählen Sie, ob Sie Sinkhole-Symbole aktivieren möchten",
            es = "Elija si desea activar los iconos de sumidero",
            fr = "Indiquez si vous souhaitez activer les icônes d'effondrement.",
            ru = "Выберите, хотите ли вы включить значки воронок",
            ko = "싱크홀 아이콘을 활성화할지 여부를 선택합니다.",
        },
    },
    FOR_ALL_SINKHOLE = {
        label = {
            en = "Icons For All",
            zh = "所有人的图标",
            de = "Icons für alle",
            es = "Iconos para todos",
            fr = "Icônes pour tous",
            ru = "Значки для всех",
            ko = "모두를 위한 아이콘",
        },
        hover = {
            en = "Choose if icons should be displayed for everyone even if they didn't go through the sinkhole or just for those that went through them.",
            zh = "选择是否应该为每个人显示图标， 即使他们没有穿过天坑，或者只为那些穿过天坑的人显示图标。",
            de = "Legen Sie fest, ob die Symbole für alle angezeigt werden sollen, auch wenn sie nicht durch das Sinkloch gegangen sind, oder nur für diejenigen, die durch das Sinkloch gegangen sind.",
            es = "Elige si los iconos deben mostrarse para todos aunque no hayan pasado por el socavón o sólo para los que lo hayan atravesado.",
            fr = "Choisissez si les icônes doivent être affichées pour tout le monde, même s'ils n'ont pas traversé le gouffre, ou seulement pour ceux qui l'ont traversé.",
            ru = "Выберите, должны ли значки отображаться для всех, даже если они не прошли через воронку, или только для тех, кто прошел через нее.",
            ko = "싱크홀을 통과하지 않았더라도 모든 사람에게 아이콘을 표시할지, 아니면 싱크홀을 통과한 사람에게만 아이콘을 표시할지 선택합니다.",
        },
        options = {
            {
                description = {
                    en = "For Everyone",
                    zh = "为每个人服务",
                    de = "Für alle",
                    es = "Para todos",
                    fr = "Pour tous",
                    ru = "Для всех",
                    ko = "모두를 위한",
                },
                hover = {
                    en = "Everyone will see all discovered sinkhole on the map",
                    zh = "每个人都会在地图上看到所有发现的天坑",
                    de = "Jeder wird alle entdeckten Sinklöcher auf der Karte sehen",
                    es = "Todo el mundo verá todos los sumideros descubiertos en el mapa",
                    fr = "Tout le monde peut voir sur la carte toutes les dolines découvertes.",
                    ru = "Все увидят на карте все обнаруженные воронки",
                    ko = "발견된 모든 싱크홀을 지도에서 확인할 수 있습니다.",
                },
            },
            {
                description = {
                    en = "For One",
                    zh = "为一",
                    de = "Für einen",
                    es = "Para uno",
                    fr = "Pour une personne",
                    ru = "Для одного",
                    ko = "하나",
                },
                hover = {
                    en = "Only those that went through the sinkhole will see them on the map",
                    zh = "只有那些穿过天坑的人才能在地图上看到他们。",
                    de = "Nur diejenigen, die durch das Sinkloch gegangen sind, sehen sie auf der Karte",
                    es = "Sólo los que pasaron por el socavón los verán en el mapa",
                    fr = "Seules les personnes ayant traversé le gouffre les verront sur la carte.",
                    ru = "Только те, кто прошел через воронку, увидят их на карте",
                    ko = "싱크홀을 통과한 사람만 지도에서 볼 수 있습니다.",
                },
            },
        },
    },
    RENAMING_SINKHOLE = {
        label = {
            en = "Renamable Sinkhole",
            zh = "可重新命名的天坑",
            de = "Umbenennbares Sinkloch",
            es = "Hundimiento renombrado",
            fr = "Renommable Sinkhole",
            ru = "Переименовываемая воронка",
            ko = "이름 변경 가능한 싱크홀",
        },
        hover = {
            en = "Choose if sinkholes can be renamed and by whom.",
            zh = "选择天坑是否可以重新命名以及由谁来命名。",
            de = "Wählen Sie, ob und von wem Senkgruben umbenannt werden können.",
            es = "Elige si se puede cambiar el nombre de los sumideros y quién puede hacerlo.",
            fr = "Choisissez si les dolines peuvent être renommées et par qui.",
            ru = "Выберите, можно ли переименовывать воронки и кем.",
            ko = "싱크홀의 이름을 변경할 수 있는지 여부와 변경할 수 있는 사용자를 선택하세요.",
        },
        options = {
            {
                description = {
                    en = "Not renameable",
                    zh = "不可重命名",
                    de = "Nicht umbenennbar",
                    es = "No renombrable",
                    fr = "Non renommable",
                    ru = "Не переименовывается",
                    ko = "이름 변경 불가",
                },
            },
            {
                description = {
                    en = "For Everyone",
                    zh = "为每个人服务",
                    de = "Für alle",
                    es = "Para todos",
                    fr = "Pour tous",
                    ru = "Для всех",
                    ko = "모두를 위한",
                },
            },
            {
                description = {
                    en = "By Admins",
                    zh = "由管理员提供",
                    de = "Von Admins",
                    es = "Por Admins",
                    fr = "Par les administrateurs",
                    ru = "Администраторами",
                    ko = "관리자",
                },
            },
        },
    },
    SHOW_NUMBERS_SINKHOLE = {
        label = {
            en = "Display Numbers/Name",
            zh = "显示号码/名称",
            de = "Nummern/Namen anzeigen",
            es = "Mostrar números/nombre",
            fr = "Affichage des numéros/noms",
            ru = "Отображение номеров/имен",
            ko = "번호/이름 표시",
        },
        hover = {
            en = "Display numbers or names on sinkhole map icons.",
            zh = "在天坑地图图标上显示数字或名称。",
            de = "Zeigen Sie Nummern oder Namen auf den Kartensymbolen für Erdfälle an.",
            es = "Mostrar números o nombres en los iconos del mapa de sumideros.",
            fr = "Afficher des numéros ou des noms sur les icônes de la carte des dolines.",
            ru = "Отображение номеров или названий на значках карты карстовых воронок.",
            ko = "싱크홀 지도 아이콘에 숫자 또는 이름을 표시합니다.",
        },
        options = {
            {
                description = {
                    en = "Nothing",
                    zh = "没有什么",
                    de = "Nichts",
                    es = "Nada",
                    fr = "Rien",
                    ru = "Ничего",
                    ko = "아무것도",
                },
            },
            {
                description = {
                    en = "Only Numbers",
                    zh = "只有数字",
                    de = "Nur Zahlen",
                    es = "Sólo números",
                    fr = "Uniquement des chiffres",
                    ru = "Только цифры",
                    ko = "숫자만",
                },
            },
            {
                description = {
                    en = "Only Names",
                    zh = "只有名字",
                    de = "Nur Namen",
                    es = "Sólo nombres",
                    fr = "Seuls les noms",
                    ru = "Только имена",
                    ko = "이름만",
                },
            },
            {
                description = {
                    en = "Numbers/Name",
                    zh = "编号/名称",
                    de = "Nummern/Namen",
                    es = "Números/Nombre",
                    fr = "Numéros/Noms",
                    ru = "Номера/название",
                    ko = "번호/이름",
                },
            },
        },
    },
    WORLD_COLORS_SINKHOLE = {
        label = {
            en = "World Colors",
            zh = "世界的颜色",
            de = "Farben der Welt",
            es = "Colores del mundo",
            fr = "Couleurs du monde",
            ru = "Краски мира",
            ko = "월드 컬러",
        },
        hover = {
            en = "Add coloring to sinkholes in world",
            zh = "为世界上的天坑添加色彩",
            de = "Einfärben von Dolinen in der Welt",
            es = "Colorear los sumideros del mundo",
            fr = "Ajouter des couleurs aux dolines dans le monde",
            ru = "Добавить раскраску в карстовые воронки мира",
            ko = "월드의 싱크홀에 색상 추가",
        },
    },
    WORLD_NUMBERS_SINKHOLE = {
        label = {
            en = "World Numbers/Name",
            zh = "世界号码/名称",
            de = "Welt-Nummern/Name",
            es = "Números mundiales/Nombre",
            fr = "Numéros/nom du monde",
            ru = "Мировые номера/названия",
            ko = "세계 번호/이름",
        },
        hover = {
            en = "Add a number or the given name above sinkholes in the world",
            zh = "在世界范围内的天坑上方添加一个数字或给定的名称",
            de = "Fügen Sie eine Nummer oder den Vornamen über die Erdfälle in der Welt hinzu",
            es = "Añadir un número o el nombre dado por encima de sumideros en el mundo",
            fr = "Ajouter un numéro ou un prénom au-dessus des dolines dans le monde",
            ru = "Добавить номер или название над карстовыми воронками в мире",
            ko = "전 세계의 싱크홀 위에 숫자 또는 주어진 이름을 추가합니다.",
        },
        options = {
            {
                description = {
                    en = "Nothing",
                    zh = "没有什么",
                    de = "Nichts",
                    es = "Nada",
                    fr = "Rien",
                    ru = "Ничего",
                    ko = "아무것도",
                },
            },
            {
                description = {
                    en = "Only Numbers",
                    zh = "只有数字",
                    de = "Nur Zahlen",
                    es = "Sólo números",
                    fr = "Uniquement des chiffres",
                    ru = "Только цифры",
                    ko = "숫자만",
                },
            },
            {
                description = {
                    en = "Only Names",
                    zh = "只有名字",
                    de = "Nur Namen",
                    es = "Sólo nombres",
                    fr = "Seuls les noms",
                    ru = "Только имена",
                    ko = "이름만",
                },
            },
            {
                description = {
                    en = "Numbers/Name",
                    zh = "编号/名称",
                    de = "Nummern/Name",
                    es = "Números/Nombre",
                    fr = "Numéros/Noms",
                    ru = "Номера/название",
                    ko = "번호/이름",
                },
            },
        },
    },
    SINKHOLE_BORDER = {
        label = {
            en = "Sinkhole Border",
            zh = "天坑边界",
            de = "Sinkloch-Grenze",
            es = "Borde del sumidero",
            fr = "Bordure de l'aven",
            ru = "Граница воронки",
            ko = "싱크홀 테두리",
        },
        hover = {
            en = "Add a colored border to sinkholes in world",
            zh = "为世界上的天坑添加一个彩色的边框",
            de = "Farbige Umrandung für Dolinen in der Welt hinzufügen",
            es = "Añadir un borde de color a los sumideros en el mundo",
            fr = "Ajouter une bordure colorée aux dolines dans le monde",
            ru = "Добавить цветную рамку к воронкам в мире",
            ko = "월드의 싱크홀에 색상 테두리 추가하기",
        },
    },
    MINIMAP_ICONS_SINKHOLE = {
        label = {
            en = "Minimap Icons",
            zh = "迷你地图图标",
            de = "Minimap-Symbole",
            es = "Iconos del minimapa",
            fr = "Icônes de mini-carte",
            ru = "Значки минимальной карты",
            ko = "미니맵 아이콘",
        },
        hover = {
            en = "Display sinkhole icons on the minimap",
            zh = "在最小地图上显示天坑图标",
            de = "Anzeige von Sinkloch-Symbolen auf der Minimap",
            es = "Mostrar iconos de sumideros en el minimapa",
            fr = "Afficher les icônes de dolines sur la minimap",
            ru = "Отображение значков воронок на карте",
            ko = "미니맵에 싱크홀 아이콘 표시",
        },
    },
    ["Wormhole Compability Options"] = {
        en = "Wormhole Compability Options",
        zh = "虫洞兼容性选项",
        de = "Optionen zur Wurmlochkompatibilität",
        es = "Opciones de compatibilidad con agujeros de gusano",
        fr = "Options de compatibilité avec les vortex",
        ru = "Варианты совместимости червоточин",
        ko = "웜홀 호환성 옵션",
    },
    MINIMAP_COMP = {
        label = {
            en = "Minimap HUD (squeek)",
            zh = "Minimap HUD (squeek)",
            de = "Minimap HUD (squeek)",
            es = "HUD del minimapa (squeek)",
            fr = "Minimap HUD (squeek)",
            ru = "Minimap HUD (писк)",
            ko = "미니맵 HUD(스퀴크)",
        },
        hover = {
            en = "Enable wormhole/sinkhole icons displaying on the minimap HUD by squeek",
            zh = "启用虫洞/沉降孔图标显示在最小地图的HUD上 by squeek",
            de = "Wurmloch-/Sinkloch-Symbole auf der Minimap-HUD von Squeek anzeigen lassen",
            es = "Activar la visualización de iconos de agujeros de gusano y sumideros en el HUD del minimapa por squeek",
            fr = "Activation de l'affichage des icônes de vortex et de trous de navigation sur la minimap HUD par squeek",
            ru = "Включение отображения иконок червоточин/потолочин на HUD миникарты by squeek",
            ko = "미니맵 HUD에 웜홀/싱크홀 아이콘을 스퀴크하여 표시하도록 설정합니다.",
        },
    },
    MINIMAPSCALE = {
        label = {
            en = "Minimap Scale Icons",
            zh = "迷你地图比例图标",
            de = "Minimap-Symbolgröße",
            es = "Iconos de escala del minimapa",
            fr = "Icônes d'échelle de la mini-carte",
            ru = "Значки масштаба минимальной карты",
            ko = "미니맵 배율 아이콘",
        },
        hover = {
            en = "Choose the scale of the minimap HUD icons.",
            zh = "选择最小地图HUD图标的比例。",
            de = "Wählen Sie den Maßstab der Minimap-HUD-Symbole.",
            es = "Elige la escala de los iconos del HUD del minimapa.",
            fr = "Choisissez l'échelle des icônes HUD de la minimap.",
            ru = "Выбор масштаба значков HUD карты.",
            ko = "미니맵 HUD 아이콘의 배율을 선택합니다.",
        },
    },
    MAPSCALE = {
        label = {
            en = "Map Scale Icons",
            zh = "地图比例尺图标",
            de = "Kartensymbolgröße",
            es = "Iconos de escala de mapa",
            fr = "Icônes d'échelle de la carte",
            ru = "Значки масштаба карты",
            ko = "지도 배율 아이콘",
        },
        hover = {
            en = "Choose the scale of the map HUD icons.",
            zh = "选择地图 HUD 图标的比例。",
            de = "Wählen Sie den Maßstab der Karten-HUD-Symbole.",
            es = "Elige la escala de los iconos del HUD del mapa.",
            fr = "Choisissez l'échelle des icônes HUD de la carte.",
            ru = "Выберите масштаб значков HUD карты.",
            ko = "지도 HUD 아이콘의 배율을 선택합니다.",
        },
    },
    DISABLE = {
        label = {
            en = "Wormhole Icons [Fixed]",
            zh = "Wormhole Icons [Fixed]",
            de = "Wormhole Icons [Fixed]",
            es = "Wormhole Icons [Fixed]",
            fr = "Wormhole Icons [Fixed]",
            ru = "Wormhole Icons [Fixed]",
            ko = "Wormhole Icons [Fixed]",
        },
        hover = {
            en = "Disable \"Wormhole Icons [Fixed]\" and/or \"Wormhole Icons + Custom Colors\" if their \"Wormhole marks disables\" option is set to Yes",
            zh = "禁用 \"虫洞图标[固定]\"和/或 \"虫洞图标+自定义颜色\"，如果他们的 \"虫洞标记禁用 \"选项被设置为 是。",
            de = "Deaktivieren Sie \"Wurmloch-Symbole [Festgelegt]\" und/oder \"Wurmloch-Symbole + Benutzerdefinierte Farben\", wenn die Option \"Wurmloch-Markierungen deaktivieren\" auf Ja gesetzt ist.",
            es = "Desactivar \"Iconos de agujeros de gusano [fijos]\" y/o \"Iconos de agujeros de gusano + colores personalizados\" si su opción \"Marcas de agujeros de gusano desactivadas\" está establecida en Sí.",
            fr = "Désactiver les \"Icônes de vortex [fixes]\" et/ou les \"Icônes de vortex + couleurs personnalisées\" si leur option \"Désactivation des marques de vortex\" est réglée sur Oui.",
            ru = "Отключить \"Значки червоточин [Фиксированные]\" и/или \"Значки червоточин + пользовательские цвета\", если для их опции \"Отключать знаки червоточин\" установлено значение Да",
            ko = "\"웜홀 마크 비활성화\" 옵션이 예로 설정된 경우 \"웜홀 아이콘 [고정]\" 및/또는 \"웜홀 아이콘 + 사용자 지정 색상\"을 비활성화합니다.",
        },
    },
    ["Wormhole Color Options"] = {
        en = "Wormhole Color Options",
        zh = "虫洞颜色选择",
        de = "Wurmloch-Farboptionen",
        es = "Opciones de color del agujero de gusano",
        fr = "Options de couleur du trou de ver",
        ru = "Варианты цвета червонца",
        ko = "웜홀 색상 옵션",
    },
    ["Sinkhole Color Options"] = {
        en = "Sinkhole Color Options",
        zh = "水坑颜色选择",
        de = "Sinkhole Farboptionen",
        es = "Opciones de color del sumidero",
        fr = "Options de couleur pour les trous d'évier",
        ru = "Варианты расцветки раковины",
        ko = "싱크홀 색상 옵션",
    },
}

name = config_strings.strings.name[language]
description = config_strings.strings.description[language]
author = "Monti"

forumthread = ""
api_version = 10

dst_compatible = true

all_clients_require_mod = true 
client_only_mod = false

icon_atlas = "modicon.xml"
icon = "modicon.tex"

priority = -1000.5

local empty_opts = {{description = "", data = 0}}
local function Title(title, hover)
    return {
        name = title,
        hover = hover,
        options = empty_opts,
        default = 0,
    }
end

folder_name = folder_name or "wormhole icons"
if folder_name:find("_Wormhole Icons Server") then
    name = name.." -dev"
end
server_filter_tags = {
"wormhole","icons","server","monti",
}


local boolean = {{description = config_strings.bool["true"][language], data = true}, {description = config_strings.bool["false"][language], data = false}}

local function getPossibleColorsOptions()
    local tab = {}
    for i = 1,20 do
        tab[i] = {description = config_strings.color_names[i][language], data = i}
    end
    return tab
end

local color_options = getPossibleColorsOptions()

local function getWormholeColorOptions(num)
    return {
        name = "WORMHOLE_COLOR_"..num,
        label = config_strings.getWormholeColorOptions.label[language]..num,
        hover = config_strings.getWormholeColorOptions.hover1[language]..num..config_strings.getWormholeColorOptions.hover2[language],
        options = color_options,
        default = num,
    }
end

local function getSinkholeColorOptions(num)
    return {
        name = "SINKHOLE_COLOR_"..num,
        label = config_strings.getSinkholeColorOptions.label[language]..num,
        hover = config_strings.getSinkholeColorOptions.hover1[language]..num..config_strings.getSinkholeColorOptions.hover2[language],
        options = color_options,
        default = 10 + num > 20 and num - 10 or 10 + num, -- to have different colors for sinkholes than for wormholes
    }
end


configuration_options = {

Title(config_strings["Utility Options"][language],""),
    {
        name = "LANGUAGE",
        label = config_strings.LANGUAGE.label[language],
        hover = config_strings.LANGUAGE.hover[language],
        options =
        {
            {description = "English", data = "en"},
            {description = "Chinese", data = "zh"},
            {description = "Russian", data = "ru"},
            {description = "Korean", data = "ko"},
            {description = "German", data = "de"},
            {description = "Spanish", data = "es"},
            {description = "French", data = "fr"},

        },
        default = "en",
    },
    {
        name = "SANITY",
        label = config_strings.SANITY.label[language],
        hover = config_strings.SANITY.hover[language],
        options = 
        {
            {description = "0", data = 0}, 
            {description = "5", data = 5},
            {description = "10", data = 10},
            {description = "15(Normal)", data = 15},
            {description = "20", data = 20},
            {description = "25", data = 25},
            {description = "30", data = 30},
            {description = "40", data = 40},
            {description = "50", data = 50},
            {description = "60", data = 60},
            {description = "70", data = 70},
            {description = "80", data = 80},
            {description = "90", data = 90},
            {description = "100", data = 100},
        },
        default = 15,
    },
    {
        name = "ICON_PLACEMENT",
        label = config_strings.ICON_PLACEMENT.label[language],
        hover = config_strings.ICON_PLACEMENT.hover[language],
        options = {
            {description = config_strings.ICON_PLACEMENT.options[1].description[language], data = 0, hover = config_strings.ICON_PLACEMENT.options[1].hover[language]}, 
            {description = config_strings.ICON_PLACEMENT.options[2].description[language], data = 1, hover = config_strings.ICON_PLACEMENT.options[2].hover[language]}, 
            {description = config_strings.ICON_PLACEMENT.options[3].description[language], data = 2, hover = config_strings.ICON_PLACEMENT.options[3].hover[language]}, 
            {description = config_strings.ICON_PLACEMENT.options[4].description[language], data = 3, hover = config_strings.ICON_PLACEMENT.options[4].hover[language]}, 
            {description = config_strings.ICON_PLACEMENT.options[5].description[language], data = 4, hover = config_strings.ICON_PLACEMENT.options[5].hover[language]}, 
            {description = config_strings.ICON_PLACEMENT.options[6].description[language], data = 5, hover = config_strings.ICON_PLACEMENT.options[6].hover[language]}, 
        },
        default = 2,
    },
    {
        name = "RENAME_FROM_MAP",
        label = config_strings.RENAME_FROM_MAP.label[language],
        hover = config_strings.RENAME_FROM_MAP.hover[language],
        options = boolean,
        default = false,
    },
    {
        name = "MAPSCALE",
        label = config_strings.MAPSCALE.label[language],
        hover = config_strings.MAPSCALE.hover[language],
        options = {
            {description = "0.1*Size", data = 0.1}, 
            {description = "0.2*Size", data = 0.2}, 
            {description = "0.3*Size", data = 0.3}, 
            {description = "0.4*Size", data = 0.4}, 
            {description = "0.5*Size", data = 0.5}, 
            {description = "0.6*Size", data = 0.6}, 
            {description = "0.7*Size", data = 0.7}, 
            {description = "0.8*Size", data = 0.8}, 
            {description = "0.9*Size", data = 0.9}, 
            {description = "Original", data = 1}, 
            {description = "1.1*Size", data = 1.1}, 
            {description = "1.2*Size", data = 1.2}, 
            {description = "1.3*Size", data = 1.3}, 
            {description = "1.4*Size", data = 1.4}, 
            {description = "1.5*Size", data = 1.5}, 
            {description = "2*Size", data = 2}, 
            {description = "3*Size", data = 3}, 
            {description = "4*Size", data = 4},  
        },
        default = 1,
    },

Title(config_strings["Wormhole Icon Options"][language],""),
    {
        name = "FOR_ALL",
        label = config_strings.FOR_ALL.label[language],
        hover = config_strings.FOR_ALL.hover[language],
        options = { 
            {description = config_strings.FOR_ALL.options[1].description[language], data = 0, hover = config_strings.FOR_ALL.options[1].hover[language]},
            {description = config_strings.FOR_ALL.options[2].description[language], data = 1, hover = config_strings.FOR_ALL.options[2].hover[language]},
        },
        default = 0,
    },
    {
        name = "RENAMING",
        label = config_strings.RENAMING.label[language],
        hover = config_strings.RENAMING.hover[language],
        options = { 
            {description = config_strings.RENAMING.options[1].description[language], data = 0},
            {description = config_strings.RENAMING.options[2].description[language], data = 1},
            {description = config_strings.RENAMING.options[3].description[language], data = 2},
        },
        default = 1,
    },
    {
        name = "SHOW_NUMBERS",
        label = config_strings.SHOW_NUMBERS.label[language],
        hover = config_strings.SHOW_NUMBERS.hover[language],
        options = { 
            {description = config_strings.SHOW_NUMBERS.options[1].description[language], data = 0},
            {description = config_strings.SHOW_NUMBERS.options[2].description[language], data = 1},
            {description = config_strings.SHOW_NUMBERS.options[3].description[language], data = 3},
            {description = config_strings.SHOW_NUMBERS.options[4].description[language], data = 2},
        },
        default = 2,
    },
    {
        name = "WORLD_COLORS",
        label = config_strings.WORLD_COLORS.label[language],
        hover = config_strings.WORLD_COLORS.hover[language],
        options = boolean,
        default = true,
    },
    {
        name = "WORLD_NUMBERS",
        label = config_strings.WORLD_NUMBERS.label[language],
        hover = config_strings.WORLD_NUMBERS.hover[language],
        options = { 
            {description = config_strings.WORLD_NUMBERS.options[1].description[language], data = 0},
            {description = config_strings.WORLD_NUMBERS.options[2].description[language], data = 1},
            {description = config_strings.WORLD_NUMBERS.options[3].description[language], data = 3},
            {description = config_strings.WORLD_NUMBERS.options[4].description[language], data = 2},
        },
        default = 2,
    },
    {
        name = "WORMHOLE_BORDER",
        label = config_strings.WORMHOLE_BORDER.label[language],
        hover = config_strings.WORMHOLE_BORDER.hover[language],
        options = boolean,
        default = true,
    },
    {
        name = "MINIMAP_ICONS",
        label = config_strings.MINIMAP_ICONS.label[language],
        hover = config_strings.MINIMAP_ICONS.hover[language],
        options = boolean,
        default = true,
    },
Title(config_strings["Sinkhole Icon Options"][language],""),
    {
        name = "SINKHOLES",
        label = config_strings.SINKHOLES.label[language],
        hover = config_strings.SINKHOLES.hover[language],
        options = boolean,
        default = true,
    },
    {
        name = "FOR_ALL_SINKHOLE",
        label = config_strings.FOR_ALL_SINKHOLE.label[language],
        hover = config_strings.FOR_ALL_SINKHOLE.hover[language],
        options = { 
            {description = config_strings.FOR_ALL_SINKHOLE.options[1].description[language], data = 0, hover = config_strings.FOR_ALL_SINKHOLE.options[1].hover[language]},
            {description = config_strings.FOR_ALL_SINKHOLE.options[2].description[language], data = 1, hover = config_strings.FOR_ALL_SINKHOLE.options[2].hover[language]},
        },
        default = 0,
    },
    {
        name = "RENAMING_SINKHOLE",
        label = config_strings.RENAMING_SINKHOLE.label[language],
        hover = config_strings.RENAMING_SINKHOLE.hover[language],
        options = { 
            {description = config_strings.RENAMING_SINKHOLE.options[1].description[language], data = 0},
            {description = config_strings.RENAMING_SINKHOLE.options[2].description[language], data = 1},
            {description = config_strings.RENAMING_SINKHOLE.options[3].description[language], data = 2},
        },
        default = 1,
    },
    {
        name = "SHOW_NUMBERS_SINKHOLE",
        label = config_strings.SHOW_NUMBERS_SINKHOLE.label[language],
        hover = config_strings.SHOW_NUMBERS_SINKHOLE.hover[language],
        options = { 
            {description = config_strings.SHOW_NUMBERS_SINKHOLE.options[1].description[language], data = 0},
            {description = config_strings.SHOW_NUMBERS_SINKHOLE.options[2].description[language], data = 1},
            {description = config_strings.SHOW_NUMBERS_SINKHOLE.options[3].description[language], data = 3},
            {description = config_strings.SHOW_NUMBERS_SINKHOLE.options[4].description[language], data = 2},
        },
        default = 2,
    },
    {
        name = "WORLD_COLORS_SINKHOLE",
        label = config_strings.WORLD_COLORS_SINKHOLE.label[language],
        hover = config_strings.WORLD_COLORS_SINKHOLE.hover[language],
        options = boolean,
        default = true,
    },
    {
        name = "WORLD_NUMBERS_SINKHOLE",
        label = config_strings.WORLD_NUMBERS_SINKHOLE.label[language],
        hover = config_strings.WORLD_NUMBERS_SINKHOLE.hover[language],
        options = { 
            {description = config_strings.WORLD_NUMBERS_SINKHOLE.options[1].description[language], data = 0},
            {description = config_strings.WORLD_NUMBERS_SINKHOLE.options[2].description[language], data = 1},
            {description = config_strings.WORLD_NUMBERS_SINKHOLE.options[3].description[language], data = 3},
            {description = config_strings.WORLD_NUMBERS_SINKHOLE.options[4].description[language], data = 2},
        },
        default = 2,
    },
    {
        name = "SINKHOLE_BORDER",
        label = config_strings.SINKHOLE_BORDER.label[language],
        hover = config_strings.SINKHOLE_BORDER.hover[language],
        options = boolean,
        default = true,
    },
    {
        name = "MINIMAP_ICONS_SINKHOLE",
        label = config_strings.MINIMAP_ICONS_SINKHOLE.label[language],
        hover = config_strings.MINIMAP_ICONS_SINKHOLE.hover[language],
        options = boolean,
        default = true,
    },

Title(config_strings["Wormhole Compability Options"][language],""),
    {
        name = "MINIMAP_COMP",
        label = config_strings.MINIMAP_COMP.label[language],
        hover = config_strings.MINIMAP_COMP.hover[language],
        options = boolean,
        default = true,
    },
    {
        name = "MINIMAPSCALE",
        label = config_strings.MINIMAPSCALE.label[language],
        hover = config_strings.MINIMAPSCALE.hover[language],
        options = { 
            {description = "0.1*Size", data = 0.1}, 
            {description = "0.2*Size", data = 0.2}, 
            {description = "0.3*Size", data = 0.3}, 
            {description = "0.4*Size", data = 0.4}, 
            {description = "0.5*Size", data = 0.5}, 
            {description = "0.6*Size", data = 0.6}, 
            {description = "0.7*Size", data = 0.7}, 
            {description = "0.8*Size", data = 0.8}, 
            {description = "0.9*Size", data = 0.9}, 
            {description = "Original", data = 1}, 
            {description = "1.1*Size", data = 1.1}, 
            {description = "1.2*Size", data = 1.2}, 
            {description = "1.3*Size", data = 1.3}, 
            {description = "1.4*Size", data = 1.4}, 
            {description = "1.5*Size", data = 1.5}, 
            {description = "2*Size", data = 2}, 
            {description = "3*Size", data = 3}, 
            {description = "4*Size", data = 4},  
        },
        default = 1,
    },
    {
        name = "DISABLE",
        label = config_strings.DISABLE.label[language],
        hover = config_strings.DISABLE.hover[language],
        options = boolean,
        default = true,
    },

Title(config_strings["Wormhole Color Options"][language],""),

}

local len = #configuration_options
for i = 1,20 do
    configuration_options[len + i] = getWormholeColorOptions(i)
end

configuration_options[len + 21] = Title(config_strings["Sinkhole Color Options"][language],"")

for i = 1,20 do
    configuration_options[len + 21 + i] = getSinkholeColorOptions(i)
end